sonar.projectKey=Anyeli_Tamara_t1
sonar.projectName=Anyeli_Tamara_t1

sonar.host.url=https://sonarqube.ingsoftware.lat/

sonar.sources=src

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/.pytest_cache/**,**/data/**,**/postman/**,**/docs/**,htmlcov/**,coverage.xml

sonar.tests=tests
sonar.test.inclusions=**/test_*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
